#! /usr/bin/python
# -*- coding: utf-8 -*-

import requests
import tokens
from selenium import webdriver
from lxml import html
import time

while True:

    url = tokens.url
    url2 = tokens.url2

    driver = webdriver.Firefox() # initiate a driver, in this case Firefox
    driver.get(url)
    request_cookies = driver.get_cookies() # storing the cookies generated by the browser

    s = requests.Session()
    response = s.get(url)

    # receiving auth token for the session
    tree = html.fromstring(response.text)
    token = list(set(tree.xpath('//input[@name="authenticity_token"]/@value')))[0]
    payload = {'user[email]': tokens.email,
               'user[password]': tokens.password,
               'authenticity_token': token,
            }
    response = s.post(url, data=payload, headers=dict(referer=url))

    #passing the cookie of the response to the browser
    resp_cookies = response.cookies.get_dict()
    response_cookies_browser = [
        {'name':name, 'value': value} for name, value in resp_cookies.items()
        ]
    c = [driver.add_cookie(c) for c in response_cookies_browser]

    driver.get(url2)

    questions = driver.find_elements_by_css_selector('[id^=question-]')
    for q in questions:
        text = q.find_element_by_css_selector('a')
        if q.text.startswith(u'Перезвон'): # check if it's a call back
            print('Перезвон ', text.get_attribute('href')) # open the question link
        elif u'банкрот' in q.text:
            print('Банкрот', text.get_attribute('href'))
        else:
            print('Saved ', text.text) # print question title
            save_button = q.find_element_by_name('commit')
            save_button.click()

    driver.close()
    time.sleep(600)
