#! /usr/bin/python

import requests
from selenium import webdriver
from lxml import html
import tokens

url = tokens.url
url2 = tokens.url2

driver = webdriver.Firefox() # initiate a driver, in this case Firefox
driver.get(url)
request_cookies = driver.get_cookies() # storing the cookies generated by the browser

s = requests.Session()
response = s.get(url)

# receiving auth token for the session
tree = html.fromstring(response.text)
token = list(set(tree.xpath('//input[@name="authenticity_token"]/@value')))[0]
payload = {'user[email]': tokens.email,
           'user[password]': tokens.password,
           'authenticity_token': token,
        }
response = s.post(url, data=payload, headers=dict(referer=url))

#passing the cookie of the response to the browser
resp_cookies = response.cookies.get_dict()
response_cookies_browser = [
    {'name':name, 'value': value} for name, value in resp_cookies.items()
    ]
c = [driver.add_cookie(c) for c in response_cookies_browser]

driver.get(url2)

questions = driver.find_elements_by_css_selector('[id^=question-]')
for q in questions:
    text = q.find_element_by_css_selector('a')
    print(text.text) # print question title
    if q.text.startswith('Прошу перезвонить'): # check if it's a call back
        link = q.find_element_by_css_selector('href')
        print(link)
        #left = q.find_element_by_id('whom_to_send_2')
        #left.select_by_visible_text('Оставить себе')
    else:
        save_button = q.find_element_by_name('commit')
        save_button.click()
